/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dgmpp.jdgmpp;

public class DamageVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DamageVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DamageVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_DamageVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEm(double value) {
    dgmppJNI.DamageVector_em_set(swigCPtr, this, value);
  }

  public double getEm() {
    return dgmppJNI.DamageVector_em_get(swigCPtr, this);
  }

  public void setThermal(double value) {
    dgmppJNI.DamageVector_thermal_set(swigCPtr, this, value);
  }

  public double getThermal() {
    return dgmppJNI.DamageVector_thermal_get(swigCPtr, this);
  }

  public void setKinetic(double value) {
    dgmppJNI.DamageVector_kinetic_set(swigCPtr, this, value);
  }

  public double getKinetic() {
    return dgmppJNI.DamageVector_kinetic_get(swigCPtr, this);
  }

  public void setExplosive(double value) {
    dgmppJNI.DamageVector_explosive_set(swigCPtr, this, value);
  }

  public double getExplosive() {
    return dgmppJNI.DamageVector_explosive_get(swigCPtr, this);
  }

  public DamageVector() {
    this(dgmppJNI.new_DamageVector(), true);
  }

}
