/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dgmpp.jdgmpp;

public class Implants {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Implants(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Implants obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_Implants(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Implants() {
    this(dgmppJNI.new_Implants__SWIG_0(), true);
  }

  public Implants(long n) {
    this(dgmppJNI.new_Implants__SWIG_1(n), true);
  }

  public long size() {
    return dgmppJNI.Implants_size(swigCPtr, this);
  }

  public long capacity() {
    return dgmppJNI.Implants_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dgmppJNI.Implants_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dgmppJNI.Implants_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dgmppJNI.Implants_clear(swigCPtr, this);
  }

  public void add(Implant x) {
    dgmppJNI.Implants_add(swigCPtr, this, Implant.getCPtr(x), x);
  }

  public Implant get(int i) {
    long cPtr = dgmppJNI.Implants_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Implant(cPtr, false);
  }

  public void set(int i, Implant val) {
    dgmppJNI.Implants_set(swigCPtr, this, i, Implant.getCPtr(val), val);
  }

}
