/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dgmpp.jdgmpp;

public class Type {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Type(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Type obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_Type(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TypeID typeID() {
    return TypeID.swigToEnum(dgmppJNI.Type_typeID(swigCPtr, this));
  }

  public GroupID groupID() {
    return GroupID.swigToEnum(dgmppJNI.Type_groupID(swigCPtr, this));
  }

  public CategoryID categoryID() {
    return CategoryID.swigToEnum(dgmppJNI.Type_categoryID(swigCPtr, this));
  }

  public Attribute attribute(AttributeID attributeID) {
    long cPtr = dgmppJNI.Type_attribute(swigCPtr, this, attributeID.swigValue());
    return (cPtr == 0) ? null : new Attribute(cPtr, false);
  }

  public Types affectors() {
    return new Types(dgmppJNI.Type_affectors(swigCPtr, this), true);
  }

  public Attributes attributes() {
    return new Attributes(dgmppJNI.Type_attributes(swigCPtr, this), true);
  }

  public Type parent() {
    long cPtr = dgmppJNI.Type_parent(swigCPtr, this);
    return (cPtr == 0) ? null : new Type(cPtr, false);
  }

  public boolean isDescendant(Type parent) {
    return dgmppJNI.Type_isDescendant(swigCPtr, this, Type.getCPtr(parent), parent);
  }

}
