/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dgmpp.jdgmpp;

public class UnitsPerSecond {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnitsPerSecond(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnitsPerSecond obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_UnitsPerSecond(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public double count() {
    return dgmppJNI.UnitsPerSecond_count(swigCPtr, this);
  }

  public UnitsPerSecond() {
    this(dgmppJNI.new_UnitsPerSecond(), true);
  }

}
