/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dgmpp;

public class Attributes {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Attributes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Attributes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_Attributes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Attributes() {
    this(dgmppJNI.new_Attributes__SWIG_0(), true);
  }

  public Attributes(long n) {
    this(dgmppJNI.new_Attributes__SWIG_1(n), true);
  }

  public long size() {
    return dgmppJNI.Attributes_size(swigCPtr, this);
  }

  public long capacity() {
    return dgmppJNI.Attributes_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dgmppJNI.Attributes_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dgmppJNI.Attributes_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dgmppJNI.Attributes_clear(swigCPtr, this);
  }

  public void add(Attribute x) {
    dgmppJNI.Attributes_add(swigCPtr, this, Attribute.getCPtr(x), x);
  }

  public Attribute get(int i) {
    long cPtr = dgmppJNI.Attributes_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Attribute(cPtr, false);
  }

  public void set(int i, Attribute val) {
    dgmppJNI.Attributes_set(swigCPtr, this, i, Attribute.getCPtr(val), val);
  }

}
