/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dgmpp;

public final class CategoryID {
  public final static int none = 0;
  public final static int owner = 1;
  public final static int celestial = 2;
  public final static int material = 4;
  public final static int ship = 6;
  public final static int module = 7;
  public final static int charge = 8;
  public final static int skill = 16;
  public final static int commodity = 17;
  public final static int drone = 18;
  public final static int implant = 20;
  public final static int starbase = 23;
  public final static int subsystem = 32;
  public final static int planetaryInteraction = 41;
  public final static int planetaryResources = 42;
  public final static int planetaryCommodities = 43;
  public final static int structure = 65;
  public final static int structureModule = 66;
  public final static int fighter = 87;
}

