/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dgmpp;

public class Charge extends Type {
  private transient long swigCPtr;

  protected Charge(long cPtr, boolean cMemoryOwn) {
    super(dgmppJNI.Charge_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Charge obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_Charge(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int size() {
    return dgmppJNI.Charge_size(swigCPtr, this);
  }

  public final static class Size {
    public final static int none = 0;
    public final static int small = 1;
    public final static int medium = 2;
    public final static int large = 3;
    public final static int xLarge = 4;
  }

}
