/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dgmpp;

public class DamagePerSecond {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DamagePerSecond(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DamagePerSecond obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_DamagePerSecond(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DamageVector count() {
    return new DamageVector(dgmppJNI.DamagePerSecond_count(swigCPtr, this), true);
  }

  public DamagePerSecond() {
    this(dgmppJNI.new_DamagePerSecond(), true);
  }

}
