/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dgmpp;

public class Drones {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Drones(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Drones obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_Drones(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Drones() {
    this(dgmppJNI.new_Drones__SWIG_0(), true);
  }

  public Drones(long n) {
    this(dgmppJNI.new_Drones__SWIG_1(n), true);
  }

  public long size() {
    return dgmppJNI.Drones_size(swigCPtr, this);
  }

  public long capacity() {
    return dgmppJNI.Drones_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dgmppJNI.Drones_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dgmppJNI.Drones_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dgmppJNI.Drones_clear(swigCPtr, this);
  }

  public void add(Drone x) {
    dgmppJNI.Drones_add(swigCPtr, this, Drone.getCPtr(x), x);
  }

  public Drone get(int i) {
    long cPtr = dgmppJNI.Drones_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Drone(cPtr, false);
  }

  public void set(int i, Drone val) {
    dgmppJNI.Drones_set(swigCPtr, this, i, Drone.getCPtr(val), val);
  }

}
