/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dgmpp;

public class Modules {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Modules(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Modules obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_Modules(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Modules() {
    this(dgmppJNI.new_Modules__SWIG_0(), true);
  }

  public Modules(long n) {
    this(dgmppJNI.new_Modules__SWIG_1(n), true);
  }

  public long size() {
    return dgmppJNI.Modules_size(swigCPtr, this);
  }

  public long capacity() {
    return dgmppJNI.Modules_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dgmppJNI.Modules_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dgmppJNI.Modules_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dgmppJNI.Modules_clear(swigCPtr, this);
  }

  public void add(Module x) {
    dgmppJNI.Modules_add(swigCPtr, this, Module.getCPtr(x), x);
  }

  public Module get(int i) {
    long cPtr = dgmppJNI.Modules_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Module(cPtr, false);
  }

  public void set(int i, Module val) {
    dgmppJNI.Modules_set(swigCPtr, this, i, Module.getCPtr(val), val);
  }

}
