/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dgmpp;

public class Resistances {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Resistances(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Resistances obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_Resistances(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  static public class Layer {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Layer(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Layer obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          dgmppJNI.delete_Resistances_Layer(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setEm(double value) {
      dgmppJNI.Resistances_Layer_em_set(swigCPtr, this, value);
    }
  
    public double getEm() {
      return dgmppJNI.Resistances_Layer_em_get(swigCPtr, this);
    }
  
    public void setThermal(double value) {
      dgmppJNI.Resistances_Layer_thermal_set(swigCPtr, this, value);
    }
  
    public double getThermal() {
      return dgmppJNI.Resistances_Layer_thermal_get(swigCPtr, this);
    }
  
    public void setKinetic(double value) {
      dgmppJNI.Resistances_Layer_kinetic_set(swigCPtr, this, value);
    }
  
    public double getKinetic() {
      return dgmppJNI.Resistances_Layer_kinetic_get(swigCPtr, this);
    }
  
    public void setExplosive(double value) {
      dgmppJNI.Resistances_Layer_explosive_set(swigCPtr, this, value);
    }
  
    public double getExplosive() {
      return dgmppJNI.Resistances_Layer_explosive_get(swigCPtr, this);
    }
  
    public Layer() {
      this(dgmppJNI.new_Resistances_Layer(), true);
    }
  
  }

  public void setShield(Resistances.Layer value) {
    dgmppJNI.Resistances_shield_set(swigCPtr, this, Resistances.Layer.getCPtr(value), value);
  }

  public Resistances.Layer getShield() {
    long cPtr = dgmppJNI.Resistances_shield_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Resistances.Layer(cPtr, false);
  }

  public void setArmor(Resistances.Layer value) {
    dgmppJNI.Resistances_armor_set(swigCPtr, this, Resistances.Layer.getCPtr(value), value);
  }

  public Resistances.Layer getArmor() {
    long cPtr = dgmppJNI.Resistances_armor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Resistances.Layer(cPtr, false);
  }

  public void setHull(Resistances.Layer value) {
    dgmppJNI.Resistances_hull_set(swigCPtr, this, Resistances.Layer.getCPtr(value), value);
  }

  public Resistances.Layer getHull() {
    long cPtr = dgmppJNI.Resistances_hull_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Resistances.Layer(cPtr, false);
  }

  public Resistances() {
    this(dgmppJNI.new_Resistances(), true);
  }

}
