/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dgmpp;

public class Tank {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Tank(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tank obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_Tank(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPassiveShield(UnitsPerSecond value) {
    dgmppJNI.Tank_passiveShield_set(swigCPtr, this, UnitsPerSecond.getCPtr(value), value);
  }

  public UnitsPerSecond getPassiveShield() {
    long cPtr = dgmppJNI.Tank_passiveShield_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UnitsPerSecond(cPtr, false);
  }

  public void setShieldRepair(UnitsPerSecond value) {
    dgmppJNI.Tank_shieldRepair_set(swigCPtr, this, UnitsPerSecond.getCPtr(value), value);
  }

  public UnitsPerSecond getShieldRepair() {
    long cPtr = dgmppJNI.Tank_shieldRepair_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UnitsPerSecond(cPtr, false);
  }

  public void setArmorRepair(UnitsPerSecond value) {
    dgmppJNI.Tank_armorRepair_set(swigCPtr, this, UnitsPerSecond.getCPtr(value), value);
  }

  public UnitsPerSecond getArmorRepair() {
    long cPtr = dgmppJNI.Tank_armorRepair_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UnitsPerSecond(cPtr, false);
  }

  public void setHullRepair(UnitsPerSecond value) {
    dgmppJNI.Tank_hullRepair_set(swigCPtr, this, UnitsPerSecond.getCPtr(value), value);
  }

  public UnitsPerSecond getHullRepair() {
    long cPtr = dgmppJNI.Tank_hullRepair_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UnitsPerSecond(cPtr, false);
  }

  public Tank() {
    this(dgmppJNI.new_Tank(), true);
  }

}
