/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dgmpp;

public class Types {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Types(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Types obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dgmppJNI.delete_Types(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Types() {
    this(dgmppJNI.new_Types__SWIG_0(), true);
  }

  public Types(long n) {
    this(dgmppJNI.new_Types__SWIG_1(n), true);
  }

  public long size() {
    return dgmppJNI.Types_size(swigCPtr, this);
  }

  public long capacity() {
    return dgmppJNI.Types_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dgmppJNI.Types_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dgmppJNI.Types_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dgmppJNI.Types_clear(swigCPtr, this);
  }

  public void add(Type x) {
    dgmppJNI.Types_add(swigCPtr, this, Type.getCPtr(x), x);
  }

  public Type get(int i) {
    long cPtr = dgmppJNI.Types_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Type(cPtr, false);
  }

  public void set(int i, Type val) {
    dgmppJNI.Types_set(swigCPtr, this, i, Type.getCPtr(val), val);
  }

}
